version: '3.8'

services:
  frontend:
    build: ./Dist_Airbnb
    ports:
      - "80:80"
    environment:
      # Replace these URLs with your actual VPS domain or IP
      - EXPO_PUBLIC_AUTH_URL=http://YOUR_VPS_IP:8001/api/auth
      - EXPO_PUBLIC_LISTING_URL=http://YOUR_VPS_IP:5000/api
    depends_on:
      - auth-service
      - list-service
    restart: unless-stopped

  auth-service:
    build: ./auth_service
    ports:
      - "8001:8001"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=YOUR_VPS_IP,YOUR_DOMAIN
    restart: unless-stopped

  list-service:
    build: ./list_service
    ports:
      - "5000:5000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001/api/auth
      - MONGO_URI=mongodb://mongo:27017/airbnb
    depends_on:
      - auth-service
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
