version: '3.8'

services:
  auth-service:
    build: ./auth_service
    ports:
      - "8001:8001"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
    volumes:
      - ./auth_service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/auth/"]
      interval: 30s
      timeout: 10s
      retries: 3

  list-service:
    build: ./list_service
    ports:
      - "5000:5000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001/api/auth
      - MONGO_URI=mongodb://mongo:27017/airbnb
    depends_on:
      - auth-service
      - mongo
    volumes:
      - ./list_service:/app

  frontend:
    build: ./Dist_Airbnb
    ports:
      - "8080:80"
    environment:
      - EXPO_PUBLIC_AUTH_URL=http://auth-service:8001/api/auth
      - EXPO_PUBLIC_LISTING_URL=http://list-service:5000/api
    depends_on:
      - auth-service
      - list-service
    volumes:
      - ./Dist_Airbnb:/usr/src/app
    # For development, don't auto-restart; adjust for production if needed

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: