name: Deploy to VPS

on:
  push:
    branches: [ "main" ]   

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # run the Dist_Airbnb deploy script on the VPS
            VPS_HOST=${{ secrets.SSH_HOST }} bash /srv/deploy_distAirbnb.sh
